/* GENERATED by tools/gen_forward_shim.py. Do not edit by hand.
 *
 * Forward-compatibility shim (Design B).
 *
 * Covers the ENUMERABLE gap: symbols a newer glibc exports that the runtime
 * we bundle does not.  It does NOT and cannot cover symbols invented after
 * this file was generated. That is Design R's job (../docs/report/README.md, and E12).
 *
 * Anything outside the covered set aborts naming the symbol.  Solo's
 * discipline: silent corruption is worse than a loud failure.
 *
 * Why stubs at all: every Mesa object is DF_BIND_NOW, so ld.so resolves the
 * whole symbol table at load.  ONE undefined symbol makes the library
 * unloadable even if that code path is never taken.  A stub converts
 * "cannot load at all" into "works unless it genuinely needs this".
 *
 *   floor  : appdir-bundled (glibc 2.44)
 *   target : glibc-2.44 (glibc 2.44)
 *   covered: 13 implementable, 0 forwardable, 22 stub-only
 *   skipped: 0 irrelevant (glibc internals / ABI markers)
 */
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <locale.h>
#include <stdio.h>
#include <stdio_ext.h>
#include <stdlib.h>
#include <string.h>
#include <sys/auxv.h>
#include <sys/ioctl.h>
#include <sys/syscall.h>
#include <termios.h>
#include <unistd.h>

#define SHIM(rt)      __attribute__((visibility("default"))) rt
#define SHIM_DATA(t)  __attribute__((visibility("default"))) t
#define SHIM_M(bits)  ((bits) == 64 ? ~0ULL : ((1ULL << (bits)) - 1ULL))

#define SHIM_FLOOR_RELEASE "2.44"

/* x86-64 and every other 64-bit port use _STAT_VER_LINUX == 1. */
#ifndef SHIM_STAT_VER
#define SHIM_STAT_VER 1
#endif

/* Declared opaquely so the shim builds on a glibc too old to know the type.
   Only ever passed straight through to the kernel. */
struct mount_attr;

extern int __cxa_atexit(void (*)(void *), void *, void *);

/* strlen without depending on the real one being interposable. */
static size_t shim_strlen(const char *s)
{ const char *p = s; while (*p) p++; return (size_t)(p - s); }

/* Loud failure, naming the symbol. Deliberately not a return-0 stub:
   a driver that reaches here would otherwise corrupt state silently. */
__attribute__((noreturn))
static void shim_fatal(const char *sym, const char *why) {
	/* write(2) rather than fprintf: reachable from contexts where stdio
	   locks are held, and this path is already fatal. */
	static const char p1[] = "\n[cross-libc-dlopen] FATAL: ";
	static const char p2[] = "\n[cross-libc-dlopen] the bundled glibc " SHIM_FLOOR_RELEASE;
	static const char p3[] = " does not provide this symbol\n"
	                         "[cross-libc-dlopen] and no implementation exists for it. "
	                         "Set CROSS_LIBC_DLOPEN_RUNTIME=host to run\n"
	                         "[cross-libc-dlopen] against the host's own libc, "
	                         "which will have it.\n";
	(void)!write(2, p1, sizeof p1 - 1);
	(void)!write(2, sym, shim_strlen(sym));
	(void)!write(2, ": ", 2);
	(void)!write(2, why, shim_strlen(why));
	(void)!write(2, p2, sizeof p2 - 1);
	(void)!write(2, p3, sizeof p3 - 1);
	abort();
}


/* ---- forward declarations (definitions are emitted alphabetically and call each other) ---- */
int _IO_feof_unlocked(FILE *f);
int _IO_ferror_unlocked(FILE *f);
int _IO_getc_unlocked(FILE *f);
int _IO_putc_unlocked(int c, FILE *f);
char * __strerror_l(int e, locale_t loc);
int at_quick_exit(void (*fn)(void));
int atexit(void (*fn)(void));
int fpurge(FILE *f);
int issetugid(void);
int membarrier(int cmd, unsigned int flags, int cpu_id);
int posix_close(int fd, int flags);
int tcgetwinsize(int fd, struct winsize *ws);
int tcsetwinsize(int fd, const struct winsize *ws);

/* ---------------- implementable ---------------- */

/* _IO_feof_unlocked: MUSL BRIDGE: macro in glibc */
SHIM(int) _IO_feof_unlocked(FILE *f) {
	/* musl exports these as real symbols; glibc defines them as macros over
	   the unsuffixed name, so the symbol is absent from libc.so.6. */
	return feof_unlocked(f);
}

/* _IO_ferror_unlocked: MUSL BRIDGE: macro in glibc */
SHIM(int) _IO_ferror_unlocked(FILE *f) {
	/* musl exports these as real symbols; glibc defines them as macros over
	   the unsuffixed name, so the symbol is absent from libc.so.6. */
	return ferror_unlocked(f);
}

/* _IO_getc_unlocked: MUSL BRIDGE: macro in glibc */
SHIM(int) _IO_getc_unlocked(FILE *f) {
	/* musl exports these as real symbols; glibc defines them as macros over
	   the unsuffixed name, so the symbol is absent from libc.so.6. */
	return getc_unlocked(f);
}

/* _IO_putc_unlocked: MUSL BRIDGE: macro in glibc */
SHIM(int) _IO_putc_unlocked(int c, FILE *f) {
	/* musl exports these as real symbols; glibc defines them as macros over
	   the unsuffixed name, so the symbol is absent from libc.so.6. */
	return putc_unlocked(c, f);
}

/* __strerror_l: MUSL BRIDGE: glibc spells it without the underscores */
SHIM(char *) __strerror_l(int e, locale_t loc) {
	return strerror_l(e, loc);
}

/* at_quick_exit: MUSL BRIDGE. Returns failure rather than register a handler with the wrong lifetime. Callers must handle a non-zero return. */
SHIM(int) at_quick_exit(void (*fn)(void)) {
	/* Same libc_nonshared.a situation as atexit. glibc's real at_quick_exit
	   runs handlers on quick_exit() only; approximating with __cxa_atexit
	   would run them on normal exit too, which is WRONG. Registering
	   nothing and reporting failure is the honest answer. */
	(void)fn;
	return -1;
}

/* atexit: MUSL BRIDGE (5.1 Design A), not a version gap: glibc keeps atexit in the static libc_nonshared.a at every release, musl exports it dynamically. Measured absent from the bundled libc.so.6. */
static void shim_atexit_thunk(void *p) {
	/* Calling through the correct prototype: no function-pointer cast, so
	   no reliance on %rdi being ignored. */
	union { void *o; void (*f)(void); } u;
	u.o = p;
	u.f();
}
SHIM(int) atexit(void (*fn)(void)) {
	union { void *o; void (*f)(void); } u;
	/* glibc marks the parameter nonnull, so it warns about this check; a
	   musl-built caller is not bound by that attribute, so keep it. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wnonnull-compare"
	if (!fn) return -1;
#pragma GCC diagnostic pop
	u.f = fn;
	/* dso_handle NULL => runs at exit(). Host objects load RTLD_NODELETE,
	   so a handler can never outlive its object. */
	return __cxa_atexit(shim_atexit_thunk, u.o, NULL);
}

/* fpurge: MUSL BRIDGE: BSD fpurge over glibc's __fpurge */
SHIM(int) fpurge(FILE *f) {
	/* musl's BSD-flavoured name for glibc's __fpurge, which is the same
	   operation with a void return. */
	__fpurge(f);
	return 0;
}

/* issetugid: MUSL BRIDGE: BSD issetugid over AT_SECURE, as musl implements it */
SHIM(int) issetugid(void) {
	/* musl exports this BSD call; glibc has never had it. The kernel already
	   answers the question through AT_SECURE, which is exactly what musl's
	   own implementation reads, so this is a faithful port, not a guess.
	   Measured: this ONE symbol was the only thing blocking libX11.so.6 and
	   libdbus-1.so.3 in the Alpine corpus test. */
	errno = 0;
	unsigned long secure = getauxval(AT_SECURE);
	if (errno == 0)
		return secure ? 1 : 0;
	/* Pre-2.19 glibc, or no auxv entry: fall back to the id comparison,
	   which misses file capabilities but never claims safety it lacks. */
	return (getuid() != geteuid() || getgid() != getegid()) ? 1 : 0;
}

/* membarrier: MUSL BRIDGE: thin syscall wrapper */
#ifndef SYS_membarrier
#define SYS_membarrier 324   /* x86-64 */
#endif
SHIM(int) membarrier(int cmd, unsigned int flags, int cpu_id) {
	return (int)syscall(SYS_membarrier, cmd, flags, cpu_id);
}

/* posix_close: MUSL BRIDGE */
SHIM(int) posix_close(int fd, int flags) {
	/* POSIX 2024. Only POSIX_CLOSE_RESTART (0) is defined, and Linux never
	   restarts close(2), so this is exactly close(). */
	(void)flags;
	return close(fd);
}

/* tcgetwinsize: MUSL BRIDGE: ioctl under a POSIX name */
SHIM(int) tcgetwinsize(int fd, struct winsize *ws) {
	/* POSIX 2024, present in musl. glibc callers use the ioctl directly. */
	return ioctl(fd, TIOCGWINSZ, ws);
}

/* tcsetwinsize: MUSL BRIDGE: ioctl under a POSIX name */
SHIM(int) tcsetwinsize(int fd, const struct winsize *ws) {
	/* POSIX 2024, present in musl. glibc callers use the ioctl directly. */
	return ioctl(fd, TIOCSWINSZ, ws);
}


/* ---------------- stub-only: abort naming the symbol ---------------- */

/* Each stub is defined under a mangled C name and given the real
   symbol name with an asm label. Defining `crypt` as void(void)
   directly collides with the prototype <unistd.h> already made
   visible; the label sets the emitted symbol without ever
   declaring a conflicting C identifier. */

/* ___environ: no audited implementation */
SHIM_DATA(char) shim_stub____environ[8] __asm__("___environ") __attribute__((aligned(16))) = { 0 };
/* __fgetwc_unlocked: no audited implementation */
SHIM(void) shim_stub___fgetwc_unlocked(void) __asm__("__fgetwc_unlocked");
SHIM(void) shim_stub___fgetwc_unlocked(void) { shim_fatal("__fgetwc_unlocked", "not implementable over this glibc"); }
/* __flt_rounds: no audited implementation */
SHIM(void) shim_stub___flt_rounds(void) __asm__("__flt_rounds");
SHIM(void) shim_stub___flt_rounds(void) { shim_fatal("__flt_rounds", "not implementable over this glibc"); }
/* __fputwc_unlocked: no audited implementation */
SHIM(void) shim_stub___fputwc_unlocked(void) __asm__("__fputwc_unlocked");
SHIM(void) shim_stub___fputwc_unlocked(void) { shim_fatal("__fputwc_unlocked", "not implementable over this glibc"); }
/* __freadahead: no audited implementation */
SHIM(void) shim_stub___freadahead(void) __asm__("__freadahead");
SHIM(void) shim_stub___freadahead(void) { shim_fatal("__freadahead", "not implementable over this glibc"); }
/* __freadptr: no audited implementation */
SHIM(void) shim_stub___freadptr(void) __asm__("__freadptr");
SHIM(void) shim_stub___freadptr(void) { shim_fatal("__freadptr", "not implementable over this glibc"); }
/* __freadptrinc: no audited implementation */
SHIM(void) shim_stub___freadptrinc(void) __asm__("__freadptrinc");
SHIM(void) shim_stub___freadptrinc(void) { shim_fatal("__freadptrinc", "not implementable over this glibc"); }
/* __fseterr: no audited implementation */
SHIM(void) shim_stub___fseterr(void) __asm__("__fseterr");
SHIM(void) shim_stub___fseterr(void) { shim_fatal("__fseterr", "not implementable over this glibc"); }
/* __lgammal_r: no audited implementation */
SHIM(void) shim_stub___lgammal_r(void) __asm__("__lgammal_r");
SHIM(void) shim_stub___lgammal_r(void) { shim_fatal("__lgammal_r", "not implementable over this glibc"); }
/* __nl_langinfo: no audited implementation */
SHIM(void) shim_stub___nl_langinfo(void) __asm__("__nl_langinfo");
SHIM(void) shim_stub___nl_langinfo(void) { shim_fatal("__nl_langinfo", "not implementable over this glibc"); }
/* __optpos: no audited implementation */
SHIM_DATA(char) shim_stub___optpos[4] __asm__("__optpos") __attribute__((aligned(16))) = { 0 };
/* __optreset: no audited implementation */
SHIM_DATA(char) shim_stub___optreset[4] __asm__("__optreset") __attribute__((aligned(16))) = { 0 };
/* __setjmp: no audited implementation */
SHIM(void) shim_stub___setjmp(void) __asm__("__setjmp");
SHIM(void) shim_stub___setjmp(void) { shim_fatal("__setjmp", "not implementable over this glibc"); }
/* __stack_chk_guard: no audited implementation */
/* Not defined on aarch64, riscv64, loongarch64: the dynamic loader
   there exports the name itself, and a definition in
   a preload wins every lookup in the process over
   the loader's own. Measured against the floor libc
   packages; issue #37. scripts/verify-artifacts.sh
   re-measures it against the target every build. */
#if !(defined(__aarch64__) || (defined(__riscv) && __riscv_xlen == 64) || defined(__loongarch__))
SHIM_DATA(char) shim_stub___stack_chk_guard[8] __asm__("__stack_chk_guard") __attribute__((aligned(16))) = { 0 };
#endif
/* __strtoimax_internal: no audited implementation */
SHIM(void) shim_stub___strtoimax_internal(void) __asm__("__strtoimax_internal");
SHIM(void) shim_stub___strtoimax_internal(void) { shim_fatal("__strtoimax_internal", "not implementable over this glibc"); }
/* __strtoumax_internal: no audited implementation */
SHIM(void) shim_stub___strtoumax_internal(void) __asm__("__strtoumax_internal");
SHIM(void) shim_stub___strtoumax_internal(void) { shim_fatal("__strtoumax_internal", "not implementable over this glibc"); }
/* _ns_flagdata: no audited implementation */
SHIM_DATA(char) shim_stub__ns_flagdata[128] __asm__("_ns_flagdata") __attribute__((aligned(16))) = { 0 };
/* fgetln: no audited implementation */
SHIM(void) shim_stub_fgetln(void) __asm__("fgetln");
SHIM(void) shim_stub_fgetln(void) { shim_fatal("fgetln", "not implementable over this glibc"); }
/* getdents: no audited implementation */
SHIM(void) shim_stub_getdents(void) __asm__("getdents");
SHIM(void) shim_stub_getdents(void) { shim_fatal("getdents", "not implementable over this glibc"); }
/* h_errno: no audited implementation */
SHIM_DATA(char) shim_stub_h_errno[4] __asm__("h_errno") __attribute__((aligned(16))) = { 0 };
/* optreset: no audited implementation */
SHIM_DATA(char) shim_stub_optreset[4] __asm__("optreset") __attribute__((aligned(16))) = { 0 };
/* sigsetjmp: no audited implementation */
SHIM(void) shim_stub_sigsetjmp(void) __asm__("sigsetjmp");
SHIM(void) shim_stub_sigsetjmp(void) { shim_fatal("sigsetjmp", "not implementable over this glibc"); }


/* ---------------- stale-shim guard ---------------- */
/* If the bundled glibc was upgraded without regenerating this file we
   would be interposing over symbols libc now provides. Detect that and
   say so loudly under CROSS_LIBC_DLOPEN_DEBUG=1 rather than fail mutely. */
static const char *const shim_covered[] = {
	"_IO_feof_unlocked",
	"_IO_ferror_unlocked",
	"_IO_getc_unlocked",
	"_IO_putc_unlocked",
	"__strerror_l",
	"at_quick_exit",
	"atexit",
	"fpurge",
	"issetugid",
	"membarrier",
	"posix_close",
	"tcgetwinsize",
	"tcsetwinsize",
	"___environ",
	"__fgetwc_unlocked",
	"__flt_rounds",
	"__fputwc_unlocked",
	"__freadahead",
	"__freadptr",
	"__freadptrinc",
	"__fseterr",
	"__lgammal_r",
	"__nl_langinfo",
	"__optpos",
	"__optreset",
	"__setjmp",
	"__stack_chk_guard",
	"__strtoimax_internal",
	"__strtoumax_internal",
	"_ns_flagdata",
	"fgetln",
	"getdents",
	"h_errno",
	"optreset",
	"sigsetjmp",
	NULL
};

__attribute__((visibility("default")))
const char *const *forward_shim_covered(void) { return shim_covered; }

__attribute__((visibility("default")))
const char *forward_shim_floor(void) { return SHIM_FLOOR_RELEASE; }

